import type { Question } from "./platform-types";

/** platform-data baseQuestions — Q&A 리졸버·데이터 공유 */
export const baseQuestions: Question[] = [
  {
    id: "q-seltos-upgrade",
    title: "셀토스 AGM60L에서 AGM70L 업그레이드 가능한가요?",
    status: "답변완료",
    category: "호환/규격",
    activityLabel: "용량업 문의",
    tags: ["셀토스", "AGM60L", "AGM70L", "업그레이드"],
    vehicleId: "seltos",
    batteryCode: "AGM60L",
    guideId: "agm-sizes",
    questionType: "업그레이드",
    featured: true,
    updatedAt: "2026-05-25",
    shortAnswer: "트레이 공간과 충전 제어 조건을 확인한 뒤 선택하는 것이 좋습니다. ISG 차량은 AGM 규격 유지가 안전합니다.",
    answer: "ISG 트림은 AGM60L 유지가 안전합니다. AGM70L은 공간·CCA·고정 브라켓을 확인한 뒤 업그레이드할 수 있으며, 교체 후 충전 제어 학습을 권장합니다.",
  },
  {
    id: "q-grandeur-upgrade",
    title: "그랜저 IG AGM80L에서 AGM95L 업그레이드 가능한가요?",
    status: "답변완료",
    category: "호환/규격",
    activityLabel: "최근 문의 많음",
    tags: ["그랜저 IG", "AGM80L", "AGM95L", "업그레이드"],
    vehicleId: "grandeur-ig",
    batteryCode: "AGM80L",
    guideId: "agm-vs-din",
    questionType: "업그레이드",
    updatedAt: "2026-05-24",
    shortAnswer: "가능하지만 트림별 장착 공간과 ISG/BMS 조건 확인이 필요합니다.",
    answer: "가능합니다. 다만 트림별 장착 공간과 ISG/BMS 조건을 확인해야 하며, AGM95L은 CCA 여유가 커 겨울철 시동에 유리합니다.",
  },
  {
    id: "q-ev6-12v",
    title: "EV6 12V 방전이 반복되는데 원인이 뭔가요?",
    status: "답변완료",
    category: "EV/방전",
    activityLabel: "EV 12V 재문의",
    tags: ["EV6", "12V", "방전"],
    vehicleId: "ev6",
    batteryCode: "EV 12V",
    guideId: "ev-12v",
    questionType: "EV 12V",
    updatedAt: "2026-05-23",
    shortAnswer: "원격 공조·앱 조회·장시간 주차 시 12V 부하가 늘 수 있습니다.",
    answer: "원격 공조·앱 조회·주차 시간이 길면 12V 부하가 늘 수 있습니다. SOH·대기전류·충전 로그를 함께 확인하고 EV 전용 12V 규격 교체를 검토하세요.",
  },
  {
    id: "q-bmw-bms",
    title: "배터리 교체 후 BMS 등록 꼭 해야 하나요?",
    status: "전문가답변",
    category: "BMS",
    activityLabel: "수입차 교체 후",
    tags: ["BMW 520i (G30)", "BMS", "AGM92Ah"],
    vehicleId: "bmw-g30",
    batteryCode: "AGM92Ah",
    guideId: "bms-register",
    questionType: "BMS/IBS",
    featured: true,
    updatedAt: "2026-05-25",
    shortAnswer: "수입차·IBS 차량은 교체 후 등록하지 않으면 충전 제어 오차와 경고가 반복될 수 있습니다.",
    answer: "충전 제어가 이전 배터리 기준으로 동작해 신품 수명이 줄거나 경고가 반복될 수 있습니다. 교체 직후 등록·충전 전압 확인을 권장합니다.",
  },
  {
    id: "q-sorento-agm",
    title: "쏘렌토 MQ4 AGM 다운그레이드해도 되나요?",
    status: "답변중",
    category: "호환",
    activityLabel: "쏘렌토 MQ4",
    tags: ["쏘렌토 MQ4", "AGM95L", "AGM80L"],
    vehicleId: "sorento-mq4",
    batteryCode: "AGM95L",
    guideId: "agm-vs-din",
    questionType: "업그레이드",
    updatedAt: "2026-05-22",
    shortAnswer: "ISG/IBS 트림은 AGM95L 유지가 안전합니다.",
    answer: "ISG/IBS 트림은 AGM95L 유지가 안전합니다. AGM80L 다운그레이드는 CCA·충전 제어 리스크가 있습니다.",
  },
  {
    id: "q-din-agm",
    title: "AGM80L 대신 DIN74L 넣어도 되나요?",
    status: "답변완료",
    category: "호환",
    activityLabel: "자주 묻는 주제",
    tags: ["AGM80L", "DIN74L", "ISG"],
    vehicleId: "grandeur-ig",
    batteryCode: "AGM80L",
    guideId: "wrong-spec",
    questionType: "AGM/DIN",
    featured: true,
    updatedAt: "2026-05-25",
    shortAnswer: "ISG/BMS 차량은 AGM 유지가 안전합니다. DIN은 충방전 특성이 달라 비권장입니다.",
    answer: "ISG/BMS 차량이라면 AGM 유지가 안전합니다. DIN74L은 크기·단자가 맞을 수 있어도 충방전 특성이 달라 권장하지 않습니다.",
  },
  {
    id: "q-agm-required",
    title: "AGM 꼭 써야 하나요?",
    status: "답변완료",
    category: "호환",
    activityLabel: "초보자 FAQ",
    tags: ["AGM", "ISG", "DIN"],
    guideId: "agm-vs-din",
    questionType: "AGM/DIN",
    featured: true,
    updatedAt: "2026-05-25",
    shortAnswer: "ISG·스마트충전·IBS/BMS 차량은 AGM/EFB 유지가 안전합니다.",
    answer: "ISG·스마트충전·IBS/BMS 차량은 AGM/EFB 유지가 안전합니다. 일반 DIN은 충전 제어와 맞지 않아 경고·수명 저하가 생길 수 있습니다.",
  },
];
