/** /__ai-audit 주요 라우트 메타 — 서버 렌더 표용 */
export type AuditRouteRow = {
  route: string;
  expectedStatus: number;
  pageFile: string;
  component: string;
  buildRevSource: string;
  headerComponent: string;
  templateComponent: string;
  knownIssue: boolean;
  note: string;
};

export const AI_AUDIT_ROUTES: AuditRouteRow[] = [
  {
    route: "/",
    expectedStatus: 200,
    pageFile: "src/app/page.tsx",
    component: "HomeSearchMain",
    buildRevSource: "layout data-build-version",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "Home hero + benefits carousel",
  },
  {
    route: "/vehicles",
    expectedStatus: 200,
    pageFile: "src/app/vehicles/page.tsx",
    component: "Vehicles hub",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "",
  },
  {
    route: "/search?q=AGM70L",
    expectedStatus: 200,
    pageFile: "src/app/search/page.tsx",
    component: "Search results",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "Spec search",
  },
  {
    route: "/search?q=쏘렌토+MQ4",
    expectedStatus: 200,
    pageFile: "src/app/search/page.tsx",
    component: "Search results",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "Vehicle search",
  },
  {
    route: "/batteries/100R",
    expectedStatus: 200,
    pageFile: "src/app/batteries/[code]/page.tsx",
    component: "BatteryDetailHub",
    buildRevSource: "data-battery-route-build-stamp",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell + BatteryDetailHub",
    knownIssue: false,
    note: "R-type commercial; no AGM95L compare CTA on hub",
  },
  {
    route: "/batteries/AGM60L",
    expectedStatus: 200,
    pageFile: "src/app/batteries/[code]/page.tsx",
    component: "BatteryDetailHub",
    buildRevSource: "data-battery-route-build-stamp",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell + BatteryDetailHub",
    knownIssue: false,
    note: "",
  },
  {
    route: "/batteries/AGM70L",
    expectedStatus: 200,
    pageFile: "src/app/batteries/[code]/page.tsx",
    component: "BatteryDetailHub",
    buildRevSource: "data-battery-route-build-stamp",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell + BatteryDetailHub",
    knownIssue: false,
    note: "",
  },
  {
    route: "/batteries/AGM80L",
    expectedStatus: 200,
    pageFile: "src/app/batteries/[code]/page.tsx",
    component: "BatteryDetailHub",
    buildRevSource: "data-battery-route-build-stamp",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell + BatteryDetailHub",
    knownIssue: false,
    note: "",
  },
  {
    route: "/batteries/AGM95L",
    expectedStatus: 200,
    pageFile: "src/app/batteries/[code]/page.tsx",
    component: "BatteryDetailHub",
    buildRevSource: "data-battery-route-build-stamp",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell + BatteryDetailHub",
    knownIssue: false,
    note: "",
  },
  {
    route: "/order-checklist",
    expectedStatus: 200,
    pageFile: "src/app/order-checklist/page.tsx",
    component: "OrderChecklistClient",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "No cross-type compare CTA on checklist",
  },
  {
    route: "/photo-check",
    expectedStatus: 200,
    pageFile: "src/app/photo-check/page.tsx",
    component: "Photo check hub",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "",
  },
  {
    route: "/symptoms",
    expectedStatus: 200,
    pageFile: "src/app/symptoms/page.tsx",
    component: "Symptoms hub",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "",
  },
  {
    route: "/compare",
    expectedStatus: 200,
    pageFile: "src/app/compare/page.tsx",
    component: "Compare page",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "100R+AGM95L pair blocked via neverSuggest",
  },
  {
    route: "/service",
    expectedStatus: 200,
    pageFile: "src/app/service/page.tsx",
    component: "ServiceHubClient",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "Delivery + outbound options",
  },
  {
    route: "/service-center",
    expectedStatus: 200,
    pageFile: "src/app/service-center/page.tsx",
    component: "ServiceCenterClient",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "Busan store map — distinct from /service",
  },
  {
    route: "/shop",
    expectedStatus: 307,
    pageFile: "src/app/shop/page.tsx",
    component: "Shop redirect",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "redirect",
    knownIssue: false,
    note: "Redirects to /search (customer shop page hidden)",
  },
  {
    route: "/guides",
    expectedStatus: 200,
    pageFile: "src/app/guides/page.tsx",
    component: "GuidesHubClient",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "",
  },
  {
    route: "/reviews",
    expectedStatus: 200,
    pageFile: "src/app/reviews/page.tsx",
    component: "ReviewsPageClient",
    buildRevSource: "layout",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "",
  },
  {
    route: "/qa",
    expectedStatus: 200,
    pageFile: "src/app/qa/page.tsx",
    component: "CommunityClient",
    buildRevSource: "data-build-stamp on qa hub",
    headerComponent: "PortalHeader",
    templateComponent: "PageShell",
    knownIssue: false,
    note: "/community redirects here",
  },
];

export const BATTERY_DETAIL_AUDIT_CODES = ["100R", "AGM60L", "AGM70L", "AGM80L", "AGM95L"] as const;
