import type { QnaCatalogEntry } from "./types";

/** 기존 platform-catalog catalogExtraQuestions — Q&A 카탈로그로 이전 */
export const LEGACY_QNA_CATALOG: QnaCatalogEntry[] = [
  {
    id: "q-blackbox",
    question: "블랙박스 때문에 배터리가 방전될 수 있나요?",
    shortAnswer:
      "상시전원·주차녹화 사용 시 대기전류가 늘 수 있습니다. 컷오프 설정과 SOH 점검이 필요합니다.",
    answer:
      "상시전원·주차녹화 사용 시 대기전류가 늘 수 있습니다. 컷오프 12.2V 이상 설정과 배터리 SOH 점검을 권장합니다. 차량별 장착 조건은 사진 확인이 안전합니다.",
    category: "방전",
    tags: ["블랙박스", "대기전류", "방전"],
    vehicleId: "sorento-mq4",
    batteryCode: "AGM95L",
    relatedGuideId: "blackbox-cutoff",
    relatedSearchQueries: ["레이 블랙박스 방전", "블랙박스 방전"],
    questionType: "방전",
    ctaType: "photo",
    featured: true,
    homeFeatured: true,
    activityLabel: "블랙박스 문의",
    updatedAt: "2026-05-21",
    priority: 90,
  },
  {
    id: "q-winter-cca",
    question: "겨울철 CCA 저하는 어떻게 확인하나요?",
    shortAnswer: "저온에서 시동 전압 강하·부하 테스트로 CCA 여유를 확인합니다.",
    answer:
      "저온에서 시동 전압 강하·부하 테스트로 CCA 여유를 확인합니다. Ah만 크다고 겨울 시동이 보장되지는 않습니다.",
    category: "겨울/CCA",
    tags: ["겨울", "CCA"],
    batteryCode: "AGM80L",
    relatedGuideId: "winter-cca",
    questionType: "방전",
    updatedAt: "2026-05-20",
  },
  {
    id: "q-voltage-121",
    question: "배터리 전압 12.1V면 위험한가요?",
    shortAnswer: "엔진 정지 상태 12.1V는 방전 구간에 가깝습니다.",
    answer:
      "엔진 정지 상태 12.1V는 방전 구간에 가깝습니다. 시동 직후 충전 전압·방전 횟수·대기전류를 함께 확인하세요.",
    category: "전압",
    tags: ["12.1V", "OCV", "방전"],
    vehicleId: "sonata",
    batteryCode: "AGM80L",
    relatedGuideId: "cca-ah",
    questionType: "방전",
    updatedAt: "2026-05-19",
  },
  {
    id: "q-manufacture",
    question: "배터리 제조일자는 어디서 확인하나요?",
    shortAnswer: "라벨의 제조 주차/월 각인을 확인하세요.",
    answer:
      "라벨의 제조 주차/월 각인을 확인합니다. 36개월 이상 경과 시 CCA·SOH 점검을 권장합니다.",
    category: "규격",
    tags: ["제조일자", "라벨"],
    relatedGuideId: "manufacture-date",
    questionType: "규격 호환",
    ctaType: "photo",
    updatedAt: "2026-05-18",
  },
  {
    id: "q-short-trip",
    question: "단거리 주행이면 배터리가 빨리 닳나요?",
    shortAnswer: "짧은 주행 반복은 충전 회복 부족으로 SOH 저하가 빨라질 수 있습니다.",
    answer:
      "짧은 주행 반복은 충전 회복이 부족해 SOH 저하가 빨라질 수 있습니다. 정기 점검과 장거리 충전 패턴이 도움이 됩니다.",
    category: "수명",
    tags: ["단거리", "SOH"],
    vehicleId: "carnival-ka4",
    relatedGuideId: "cca-ah",
    questionType: "방전",
    updatedAt: "2026-05-17",
  },
  {
    id: "q-porter2-year",
    question: "포터2는 왜 90R과 100R이 나뉘나요?",
    shortAnswer:
      "연식에 따라 적용 규격이 달라질 수 있습니다. 2020년 전후로 90R·100R 후보가 나뉘므로 연식·사진 확인이 필요합니다.",
    answer:
      "포터2는 연식·트림에 따라 90R(GB90R)과 100R(GB100R) 후보가 나뉩니다. 크기가 비슷해도 호환되지 않을 수 있어 연식 또는 현재 장착 배터리 사진 확인이 필요합니다.",
    category: "연식/규격",
    tags: ["포터2", "90R", "100R", "연식"],
    vehicleId: "porter2-new",
    batteryCode: "100R",
    relatedBatteryCodes: ["90R", "100R"],
    relatedVehicleSlugs: ["porter2-new", "porter2-old"],
    relatedSearchQueries: ["포터2 배터리", "포터2 20년식", "포터2 2019"],
    relatedGuideId: "wrong-spec",
    questionType: "상용차",
    homeFeatured: true,
    featured: true,
    priority: 95,
    ctaType: "photo",
    updatedAt: "2026-05-28",
  },
  {
    id: "q-staria-80r",
    question: "스타리아는 AGM80L이 아니라 AGM80R인가요?",
    shortAnswer: "스타리아는 AGM80R 기준으로 확인하는 경우가 많습니다.",
    answer:
      "스타리아(US4)는 디젤·LPG 모두 AGM80R로 확인하는 경우가 많습니다. AGM80L과 R단자 혼동이 잦아 사진 확인을 권장합니다.",
    category: "단자/규격",
    tags: ["스타리아", "AGM80R", "AGM80L", "단자방향"],
    vehicleId: "staria-us4",
    batteryCode: "AGM80R",
    relatedGuideId: "terminal-lr",
    questionType: "단자 방향",
    featured: true,
    updatedAt: "2026-05-23",
  },
  {
    id: "q-agm80lr-diff",
    question: "AGM80L과 AGM80R은 뭐가 다른가요?",
    shortAnswer: "용량 계열은 같지만 플러스 단자 위치(L/R)가 다릅니다.",
    answer:
      "80은 Ah 계열이고 L/R은 플러스 단자 위치입니다. 방향이 다르면 케이블·클램프가 맞지 않아 장착이 어렵습니다.",
    category: "규격",
    tags: ["AGM80L", "AGM80R", "단자방향"],
    relatedGuideId: "terminal-lr",
    questionType: "단자 방향",
    updatedAt: "2026-05-22",
  },
  {
    id: "q-g80-rg3",
    question: "G80 RG3는 AGM95R이 맞나요?",
    shortAnswer: "G80 RG3는 AGM95R/R 계열 문의가 많지만, 연식·장착 배터리 기준 확인이 안전합니다.",
    answer:
      "G80 RG3(3세대)는 AGM95R/R 계열로 문의가 많습니다. 세대·연식·단자 방향에 따라 달라질 수 있어 사진 확인을 권장합니다.",
    category: "차종/규격",
    tags: ["G80", "G80 RG3", "AGM95R", "제네시스"],
    vehicleId: "g80-rg3",
    batteryCode: "AGM95R",
    questionType: "수입차",
    ctaType: "photo",
    updatedAt: "2026-05-21",
  },
  {
    id: "q-ev6-vs-agm60",
    question: "EV6 12V 배터리는 일반 AGM60L과 다른가요?",
    shortAnswer: "EV 12V는 통신·대기전류 특성이 달라 EV 전용 규격 확인이 필요합니다.",
    answer:
      "전기차 12V는 일반 승용 AGM60L과 용도·충전 패턴이 다릅니다. EV 전용 12V 규격과 SOH·대기전류를 함께 확인하세요.",
    category: "EV/규격",
    tags: ["EV6", "EV 12V", "AGM60L"],
    vehicleId: "ev6",
    batteryCode: "EV 12V",
    relatedBatteryCodes: ["EV 12V", "AGM60L"],
    relatedSearchQueries: ["EV6 보조배터리", "아이오닉5 배터리"],
    relatedGuideId: "ev-12v",
    questionType: "EV 12V",
    homeFeatured: true,
    priority: 88,
    updatedAt: "2026-05-20",
  },
  {
    id: "q-blackbox-upgrade",
    question: "블랙박스 때문에 방전이 자주 되면 배터리를 키우면 되나요?",
    shortAnswer: "용량업만으로 해결되지 않을 수 있습니다. 컷오프·대기전류 점검이 우선입니다.",
    answer:
      "무조건 큰 배터리로 올리기보다 컷오프 설정·대기전류·SOH를 먼저 확인하세요. ISG 차량은 AGM 규격과 충전 제어 조건도 함께 봐야 합니다.",
    category: "방전/업그레이드",
    tags: ["블랙박스", "방전", "업그레이드"],
    vehicleId: "seltos",
    batteryCode: "AGM60L",
    relatedGuideId: "blackbox-cutoff",
    questionType: "방전",
    updatedAt: "2026-05-19",
  },
  {
    id: "q-din-to-agm",
    question: "DIN74L 대신 AGM80L을 넣어도 되나요?",
    shortAnswer: "ISG 차량은 AGM80L 유지가 안전합니다. DIN에서 AGM으로 올리는 것은 조건 확인 후 가능합니다.",
    answer:
      "ISG/BMS 차량은 AGM80L 유지가 안전합니다. DIN74L에서 AGM80L로 올릴 때는 크기·단자·충전 제어 학습을 확인해야 합니다.",
    category: "호환",
    tags: ["DIN74L", "AGM80L", "ISG"],
    vehicleId: "grandeur-ig",
    batteryCode: "AGM80L",
    relatedGuideId: "agm-vs-din",
    questionType: "AGM/DIN",
    updatedAt: "2026-05-18",
  },
  {
    id: "q-warning-light",
    question: "배터리 교체 후 경고등이 뜨면 어떻게 해야 하나요?",
    shortAnswer: "BMS/IBS 등록·충전 전압·규격 일치 여부를 먼저 확인하세요.",
    answer:
      "수입차·IBS 차량은 교체 후 등록 누락, 규격 불일치, 센서 학습 미완료로 경고가 뜰 수 있습니다. 등록·전압·규격을 순서대로 점검하세요.",
    category: "BMS/경고",
    tags: ["경고등", "BMS", "교체"],
    vehicleId: "bmw-g30",
    relatedGuideId: "bms-register",
    questionType: "BMS/IBS",
    updatedAt: "2026-05-17",
  },
  {
    id: "q-import-photo",
    question: "수입차는 왜 사진 확인이 필요한가요?",
    shortAnswer: "연식·트림·단자 방향·BMS 조건이 국산차보다 헷갈리기 쉽습니다.",
    answer:
      "수입차는 연식·트림·Ah·단자 방향·BMS 등록 조건이 모델별로 달라 사진·라벨 확인이 오주문을 줄입니다.",
    category: "수입차",
    tags: ["수입차", "사진확인", "단자방향"],
    vehicleId: "bmw-g30",
    relatedGuideId: "wrong-spec",
    questionType: "수입차",
    ctaType: "photo",
    updatedAt: "2026-05-16",
  },
  {
    id: "q-agm-discharge-life",
    question: "AGM 배터리도 방전되면 수명이 줄어드나요?",
    shortAnswer: "깊은 방전 반복은 AGM도 SOH·CCA 저하를 가속할 수 있습니다.",
    answer:
      "AGM도 과방전·반복 방전이 누적되면 SOH와 CCA가 빠르게 떨어질 수 있습니다. 방전 원인(대기전류·블랙박스)도 함께 점검하세요.",
    category: "수명",
    tags: ["AGM", "방전", "SOH"],
    batteryCode: "AGM80L",
    relatedGuideId: "cca-ah",
    questionType: "방전",
    updatedAt: "2026-05-15",
  },
];
