/**
 * Vehicle-first canonical registry — DB 원본 미변경, 검색 alias만 정의
 */
export type VehicleCanonicalEntry = {
  canonicalKey: string;
  displayName: string;
  brand: string;
  model: string;
  generation: string | null;
  fuel: string | null;
  assetId?: string;
  catalogId?: string;
  dbQuery: string;
  /** 긴 alias일수록 높은 specificity (정렬용) */
  specificity: number;
  aliases: string[];
};

function aliasRegex(alias: string): RegExp {
  const escaped = alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s*");
  return new RegExp(escaped, "i");
}

export function canonicalAliasMatches(query: string, entry: VehicleCanonicalEntry): boolean {
  const q = query.replace(/\s*배터리\s*$/i, "").trim();
  return entry.aliases.some((a) => aliasRegex(a).test(q));
}

/** 구체적 항목이 먼저 오도록 specificity 내림차순 정렬 */
export const VEHICLE_CANONICAL_REGISTRY: VehicleCanonicalEntry[] = [
  // —— 기아 쏘렌토 (하이브리드 우선) ——
  {
    canonicalKey: "kia-sorento-mq4-hybrid",
    displayName: "기아 쏘렌토 MQ4 하이브리드",
    brand: "기아",
    model: "쏘렌토",
    generation: "MQ4",
    fuel: "하이브리드",
    assetId: "sorento-mq4",
    catalogId: "sorento-mq4",
    dbQuery: "쏘렌토 MQ4",
    specificity: 100,
    aliases: [
      "쏘렌토 MQ4 하이브리드",
      "쏘렌토 4세대 하이브리드",
      "쏘렌토 4세대 하브",
      "쏘렌토 하이브리드",
      "쏘렌토 하브",
      "쏘렌토 HEV",
      "쏘렌토 mq4 hev",
      "쏘렌토 mq4 하브",
      "sorento mq4 hybrid",
      "sorento hev",
    ],
  },
  {
    canonicalKey: "kia-sorento-mq4",
    displayName: "기아 쏘렌토 MQ4",
    brand: "기아",
    model: "쏘렌토",
    generation: "MQ4",
    fuel: null,
    assetId: "sorento-mq4",
    catalogId: "sorento-mq4",
    dbQuery: "쏘렌토 MQ4",
    specificity: 80,
    aliases: ["쏘렌토 MQ4", "쏘렌토 4세대", "쏘렌토 2020", "쏘렌토 2021", "쏘렌토 2022", "sorento mq4"],
  },
  {
    canonicalKey: "kia-sorento",
    displayName: "기아 쏘렌토",
    brand: "기아",
    model: "쏘렌토",
    generation: null,
    fuel: null,
    dbQuery: "쏘렌토",
    specificity: 50,
    aliases: ["쏘렌토", "sorento"],
  },

  // —— 하이브리드 필수 ——
  {
    canonicalKey: "hyundai-santafe-mx5-hybrid",
    displayName: "현대 싼타페 MX5 하이브리드",
    brand: "현대",
    model: "싼타페",
    generation: "MX5",
    fuel: "하이브리드",
    assetId: "santafe-mx5",
    dbQuery: "싼타페 MX5",
    specificity: 100,
    aliases: ["싼타페 MX5 하이브리드", "싼타페 하이브리드", "싼타페 HEV", "싼타페 하브", "싼타페 mx5 hev"],
  },
  {
    canonicalKey: "hyundai-santafe-mx5",
    displayName: "현대 싼타페 MX5",
    brand: "현대",
    model: "싼타페",
    generation: "MX5",
    fuel: null,
    assetId: "santafe-mx5",
    dbQuery: "싼타페 MX5",
    specificity: 80,
    aliases: ["싼타페 MX5", "싼타페 4세대", "디올뉴 싼타페"],
  },
  {
    canonicalKey: "kia-sportage-nq5-hybrid",
    displayName: "기아 스포티지 NQ5 하이브리드",
    brand: "기아",
    model: "스포티지",
    generation: "NQ5",
    fuel: "하이브리드",
    assetId: "sportage-nq5",
    catalogId: "sportage-nq5",
    dbQuery: "스포티지",
    specificity: 100,
    aliases: ["스포티지 NQ5 하이브리드", "스포티지 하이브리드", "스포티지 HEV", "스포티지 하브"],
  },
  {
    canonicalKey: "kia-sportage-nq5",
    displayName: "기아 스포티지 NQ5",
    brand: "기아",
    model: "스포티지",
    generation: "NQ5",
    fuel: null,
    dbQuery: "스포티지",
    specificity: 80,
    aliases: ["스포티지 NQ5", "스포티지 5세대"],
  },
  {
    canonicalKey: "kia-k8-hybrid",
    displayName: "기아 K8 하이브리드",
    brand: "기아",
    model: "K8",
    generation: "GL3",
    fuel: "하이브리드",
    assetId: "k8-gl3",
    dbQuery: "K8",
    specificity: 100,
    aliases: ["K8 하이브리드", "K8 HEV", "케이8 하이브리드", "K8 GL3 하이브리드"],
  },
  {
    canonicalKey: "kia-k8",
    displayName: "기아 K8",
    brand: "기아",
    model: "K8",
    generation: "GL3",
    fuel: null,
    assetId: "k8-gl3",
    dbQuery: "K8",
    specificity: 80,
    aliases: ["K8", "K8 GL3", "케이8", "케이8"],
  },
  {
    canonicalKey: "hyundai-grandeur-gn7-hybrid",
    displayName: "현대 그랜저 GN7 하이브리드",
    brand: "현대",
    model: "그랜저",
    generation: "GN7",
    fuel: "하이브리드",
    assetId: "grandeur-gn7",
    catalogId: "grandeur-gn7",
    dbQuery: "그랜저 GN7",
    specificity: 100,
    aliases: ["그랜저 GN7 하이브리드", "그랜저 하이브리드", "그랜저 HEV", "디올뉴 그랜저 하이브리드"],
  },
  {
    canonicalKey: "hyundai-grandeur-gn7",
    displayName: "현대 그랜저 GN7",
    brand: "현대",
    model: "그랜저",
    generation: "GN7",
    fuel: null,
    assetId: "grandeur-gn7",
    catalogId: "grandeur-gn7",
    dbQuery: "그랜저 GN7",
    specificity: 80,
    aliases: ["그랜저 GN7", "디올뉴 그랜저"],
  },
  {
    canonicalKey: "hyundai-tucson-nx4-hybrid",
    displayName: "현대 투싼 NX4 하이브리드",
    brand: "현대",
    model: "투싼",
    generation: "NX4",
    fuel: "하이브리드",
    assetId: "tucson-nx4",
    catalogId: "tucson-nx4",
    dbQuery: "투싼 NX4",
    specificity: 100,
    aliases: ["투싼 NX4 하이브리드", "투싼 하이브리드", "투싼 HEV", "투싼 4세대 하이브리드"],
  },
  {
    canonicalKey: "hyundai-tucson-nx4",
    displayName: "현대 투싼 NX4",
    brand: "현대",
    model: "투싼",
    generation: "NX4",
    fuel: null,
    assetId: "tucson-nx4",
    catalogId: "tucson-nx4",
    dbQuery: "투싼 NX4",
    specificity: 80,
    aliases: ["투싼 NX4", "투싼 4세대"],
  },

  // —— 전기 ——
  {
    canonicalKey: "hyundai-ioniq5-ne",
    displayName: "현대 아이오닉5",
    brand: "현대",
    model: "아이오닉5",
    generation: "NE",
    fuel: "전기",
    assetId: "ioniq5-ne",
    catalogId: "ioniq5",
    dbQuery: "아이오닉5",
    specificity: 95,
    aliases: ["아이오닉5 전기", "아이오닉 5", "IONIQ5", "IONIQ 5", "아이오닉5 NE"],
  },
  {
    canonicalKey: "hyundai-ioniq6-ce",
    displayName: "현대 아이오닉6",
    brand: "현대",
    model: "아이오닉6",
    generation: "CE",
    fuel: "전기",
    dbQuery: "아이오닉6",
    specificity: 95,
    aliases: ["아이오닉6 전기", "아이오닉 6", "IONIQ6", "IONIQ 6", "아이오닉6 CE"],
  },
  {
    canonicalKey: "kia-ev6-cv",
    displayName: "기아 EV6",
    brand: "기아",
    model: "EV6",
    generation: "CV",
    fuel: "전기",
    assetId: "ev6",
    catalogId: "ev6",
    dbQuery: "EV6",
    specificity: 95,
    aliases: ["EV6", "EV6 보조배터리", "EV6 전기", "EV6 CV", "ev6 electric", "보조배터리 EV6"],
  },

  // —— 기타 자주 쓰는 차량 (기존 alias 유지) ——
  {
    canonicalKey: "hyundai-grandeur",
    displayName: "현대 그랜저",
    brand: "현대",
    model: "그랜저",
    generation: null,
    fuel: null,
    assetId: "grandeur-gn7",
    catalogId: "grandeur-gn7",
    dbQuery: "그랜저",
    specificity: 45,
    aliases: ["그랜저"],
  },
  {
    canonicalKey: "hyundai-grandeur-ig",
    displayName: "현대 그랜저 IG",
    brand: "현대",
    model: "그랜저",
    generation: "IG",
    fuel: null,
    assetId: "grandeur-ig",
    catalogId: "grandeur-ig",
    dbQuery: "그랜저 IG",
    specificity: 80,
    aliases: ["그랜저 IG"],
  },
  {
    canonicalKey: "hyundai-avante-cn7",
    displayName: "현대 아반떼 CN7",
    brand: "현대",
    model: "아반떼",
    generation: "CN7",
    fuel: null,
    assetId: "avante-cn7",
    dbQuery: "아반떼 CN7",
    specificity: 80,
    aliases: ["아반떼 CN7", "아반떼"],
  },
  {
    canonicalKey: "kia-carnival-ka4",
    displayName: "기아 카니발 KA4",
    brand: "기아",
    model: "카니발",
    generation: "KA4",
    fuel: null,
    assetId: "carnival-ka4",
    catalogId: "carnival-ka4",
    dbQuery: "카니발 KA4",
    specificity: 80,
    aliases: ["카니발 KA4", "카니발 4세대", "카니발"],
  },
  {
    canonicalKey: "kia-seltos-sp2",
    displayName: "기아 셀토스 SP2",
    brand: "기아",
    model: "셀토스",
    generation: "SP2",
    fuel: null,
    assetId: "seltos-sp2",
    catalogId: "seltos",
    dbQuery: "셀토스 SP2",
    specificity: 80,
    aliases: ["셀토스 SP2", "셀토스"],
  },
  {
    canonicalKey: "kia-ray",
    displayName: "기아 레이",
    brand: "기아",
    model: "레이",
    generation: "TAM",
    fuel: null,
    dbQuery: "레이",
    specificity: 70,
    aliases: ["레이 TAM", "레이"],
  },
  {
    canonicalKey: "hyundai-staria-us4",
    displayName: "현대 스타리아 US4",
    brand: "현대",
    model: "스타리아",
    generation: "US4",
    fuel: null,
    assetId: "staria-us4",
    dbQuery: "스타리아",
    specificity: 80,
    aliases: ["스타리아 US4", "스타리아"],
  },
  {
    canonicalKey: "hyundai-kona",
    displayName: "현대 코나",
    brand: "현대",
    model: "코나",
    generation: null,
    fuel: null,
    dbQuery: "코나",
    specificity: 60,
    aliases: ["코나"],
  },
  {
    canonicalKey: "genesis-gv70",
    displayName: "제네시스 GV70",
    brand: "제네시스",
    model: "GV70",
    generation: "JK1",
    fuel: null,
    dbQuery: "GV70",
    specificity: 75,
    aliases: ["GV70 JK1", "GV70"],
  },
  {
    canonicalKey: "audi-a6-c8",
    displayName: "아우디 A6 C8",
    brand: "아우디",
    model: "A6",
    generation: "C8",
    fuel: null,
    dbQuery: "A6 C8",
    specificity: 80,
    aliases: ["A6 C8", "아우디 A6", "A6"],
  },
  {
    canonicalKey: "kg-rexton-sports-y400",
    displayName: "KG/쌍용 렉스턴 스포츠 Y400",
    brand: "쌍용",
    model: "렉스턴 스포츠",
    generation: "Y400",
    fuel: null,
    dbQuery: "렉스턴 스포츠",
    specificity: 85,
    aliases: ["렉스턴 스포츠 Y400", "렉스턴 스포츠", "렉스턴스포츠"],
  },
  {
    canonicalKey: "kia-bongo3",
    displayName: "기아 봉고3",
    brand: "기아",
    model: "봉고3",
    generation: null,
    fuel: null,
    dbQuery: "봉고3",
    specificity: 70,
    aliases: ["봉고3", "봉고 3"],
  },
  {
    canonicalKey: "hyundai-porter2-from2020",
    displayName: "현대 포터2 2020년형 이후",
    brand: "현대",
    model: "포터2",
    generation: "2020년형 이후",
    fuel: null,
    assetId: "porter2-new",
    catalogId: "porter2-new",
    dbQuery: "포터2",
    specificity: 92,
    aliases: [
      "포터2 20년식",
      "포터2 2020",
      "포터2 2020년식",
      "포터2 2020년형",
      "포터2 2020년 이후",
      "포터2 20년 이후",
      "포터 2 20년식",
      "포터 2 2020",
      "포터2 21년식",
      "포터2 22년식",
      "포터2 23년식",
      "포터2 24년식",
      "포터2 25년식",
      "포터2 2021",
      "포터2 2022",
      "포터2 2023",
      "포터2 2024",
      "포터2 2025",
    ],
  },
  {
    canonicalKey: "hyundai-porter2-until2019",
    displayName: "현대 포터2 2019년 이전",
    brand: "현대",
    model: "포터2",
    generation: "2019년 이전",
    fuel: null,
    assetId: "porter2-old",
    catalogId: "porter2-old",
    dbQuery: "포터2",
    specificity: 88,
    aliases: ["포터2 19년식", "포터2 2019", "포터2 2019년식", "포터2 2019년 이전"],
  },
  {
    canonicalKey: "hyundai-porter2",
    displayName: "현대 포터2",
    brand: "현대",
    model: "포터2",
    generation: null,
    fuel: null,
    dbQuery: "포터2",
    specificity: 70,
    aliases: ["포터2", "포터 2"],
  },
].sort((a, b) => b.specificity - a.specificity);

export { aliasRegex };
